version: '3.5'

services:
    node-app:
        build: .
        container_name: node-app
        expose:
            - 3000
        environment:
            - MONGODB_HOST=mongodb://mongodb:27017/devops
        depends_on:
            - mongodb
        networks:
            - backbone

    mongodb:
        container_name: mongodb
        image: mongo:3.4
        volumes:
            - '/data/db:/data/db'
        networks:
            - backbone

networks:
    backbone:
        external: true
        name: backbone
